# Use a base image with the necessary build tools
FROM openjdk:17-jdk-slim

# Install necessary packages
RUN apt-get update && \
    apt-get install -y \
    wget \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables for Android SDK
ENV ANDROID_SDK_ROOT=/sdk
ENV PATH=${PATH}:${ANDROID_SDK_ROOT}/tools:${ANDROID_SDK_ROOT}/platform-tools

# Download and install Android SDK
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O /sdk.zip && \
    unzip /sdk.zip -d ${ANDROID_SDK_ROOT} && \
    rm /sdk.zip

# Install SDK components
RUN yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses && \
    sdkmanager --update && \
    sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

# Set working directory
WORKDIR /app

# Copy the entire project
COPY . .

# Build the project
RUN ./gradlew assembleRelease

# Define the command to run your app
CMD ["./gradlew", "run"]
